# Generated by Django 4.2.14 on 2024-08-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artblog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
